- name: create /home/opc/ha_config directory
  become: true
  file:
    path: /home/opc/ha_config
    state: directory
  when: fs_ha|bool

- name: create corosync file
  template:
    src: _corosync.j2
    dest: /home/opc/ha_config/corosync
  when: fs_ha|bool

- name: create corosync.conf with 1 ring
  template:
    src: _corosync.conf.1ring.j2
    dest: /home/opc/ha_config/corosync.conf
  when: fs_ha|bool

- name: create logrotate.d corosync file
  template:
    src: _logrotate.d_corosync.j2
    dest: /etc/logrotate.d/corosync
    force: true
    backup: true
    owner: root
    group: root
    mode: 0644
  when: fs_ha|bool