- name: Set facts
  ansible.builtin.shell: ls /dev/* | grep nvme | grep n1 | wc -l
  register: nvme_cnt

- name: Set nfs thread count 
  ansible.builtin.lineinfile:
    path: /etc/nfs.conf
    regexp: '^threads'
    line: threads=16
  when: 
    - ansible_facts['processor_cores']*ansible_facts['processor_count'] > 16

- name: Remove strings from block_size if present
  ansible.builtin.set_fact:
    lvm_stripe_size: "{{ block_size | replace('kb', '') | replace('KB', '') | replace('k', '') | replace('K', '') }}"

#find_UHP_block_volume
- name: 
  block:
    - name: Waiting for UHP block plugin to do batch iscsi login to complete
      ansible.builtin.wait_for:
        path: /dev/mapper/mpatha

    - name: Set blk_lst and blk_cnt when fs_ha and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when: 
    - use_uhp|bool == true
    - fs_ha|bool == true

- name: 
  block:
    - name: Set blk_lst and blk_cnt when fs_ha is not defined and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
    - use_uhp|bool == true
    - fs_ha|bool == false

#find_block_volumes
- name: Waiting for block-attach of Block volumes to complete
  ansible.builtin.wait_for:
    path: /tmp/block-attach.complete

- name:
  block:
    - name: Set blk_lst and blk_cnt when fs_ha is defined and use_uhp is not defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$"
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - fs_ha|bool == true
     - use_uhp|bool == false

- name:
  block:
    - name: Set blk_lst and blk_cnt when fs_ha and use_uhp is not defined
      shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - fs_ha|bool == false
     - use_uhp|bool == false

- name:
  block:
    - name: Find nvme disks
      shell: ls /dev/* | grep nvme | grep n1 | sort
      register: nvme_lst

    - shell: ls /dev/* | grep nvme | grep n1 | wc -l
      register: nvme_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - nvme_cnt | int > 0