- name: Set nfs thread count 
  ansible.builtin.lineinfile:
    path: /etc/nfs.conf
    regexp: '^threads'
    line: threads=16
  when: 
    - ansible_facts['processor_cores']*ansible_facts['processor_count'] > 16
    - "'storage' in group_names"

- name: Remove strings from block_size if present
  ansible.builtin.set_fact:
    lvm_stripe_size: "{{ block_size | replace('kb', '') | replace('KB', '') | replace('k', '') | replace('K', '') }}"
 
- name: Set fs0 name
  ansible.builtin.set_fact:
    mount_point: /mnt/{{ fs0_name }}
    disk_name: disk0
  when: use_uhp|bool == true

#find_UHP_block_volume
- name: 
  block:
    - name: Waiting for UHP block plugin to do batch iscsi login to complete
      ansible.builtin.wait_for:
        path: /dev/mapper/mpatha

    - name: set blk_lst and blk_cnt when fs_ha is and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | sort
      register: blk_lst

    - shell: ls  /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when: 
    - "'storage' in group_names"
    - use_uhp|bool == true
    - fs_ha|bool == true

- name: 
  block:
    - name: set blk_lst and blk_cnt when fs_ha not defined
      shell: ls  /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | sort
      register: blk_lst_uhp

    - shell: ls  /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | wc -l
      register: blk_cnt_uhp

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
    - "'storage' in group_names"
    - use_uhp|bool == true
    - fs_ha|bool == false

#find_block_volumes
- name: Waiting for block-attach of Block volumes to complete
  ansible.builtin.wait_for:
    path: /tmp/block-attach.complete
  when: "'storage' in group_names"

- name:
  block:
    - name: set blk_lst and blk_cnt when fs_ha is not defined and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$"
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
    - set_fact: 
        blk_lst_reg: "{{ blk_lst.stdout }}"
        blk_cnt_reg: "{{ blk_cnt.stdout }}"
  when:
     - "'storage' in group_names"
     - fs_ha|bool == true
     - use_uhp|bool == false

- name:
  block:
    - name: set blk_lst and blk_cnt when fs_ha and use_uhp is not defined
      shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
    - set_fact:
        blk_lst_reg: "{{ blk_lst.stdout }}"
        blk_cnt_reg: "{{ blk_cnt.stdout }}"
  when:
     - "'storage' in group_names"
     - fs_ha|bool == false
     - use_uhp|bool == false
