- hosts: quorum
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Stop firewalld
    ansible.builtin.include_role:
      name: firewall

  - name: Install packages
    ansible.builtin.include_role:
      name: packages

  - name: Configure corosync-qnetd
    ansible.builtin.include_role:
      name: quorum

- hosts: storage
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: stop firewalld
    ansible.builtin.include_role:
      name: firewall

  - name: install packages
    ansible.builtin.include_role:
      name: packages

  - name: Configure Network
    ansible.builtin.include_role:
      name: network
    
  - name: Configure Storage
    ansible.builtin.include_role:
      name: storage

  - name: Configure corosync
    ansible.builtin.include_role:
      name: corosync
    when: fs_ha|bool

  - name: Restart cron
    ansible.builtin.include_role:
      name: cron

  - name: Configure cluster resource files
    ansible.builtin.include_role:
      name: res_files
    when: fs_ha|bool
  
  # only for VMs - since they come up too quickly before stonith fencing completes.
  - name: add 30s delay for VM instances for corosync service
    lineinfile:
      path: /usr/lib/systemd/system/corosync.service
      insertbefore: 'ExecStart=/usr/share/corosync/corosync start'
      line: 'ExecStartPre=/bin/sleep 30'
      state: present
      create: no
    when: (fs_ha|bool and (not {{ storage_server_dual_nics }}))|default(false)|bool

  - name: Configure NFS
    ansible.builtin.include_role:
      name: nfs_server

  - name: Configure HA service
    ansible.builtin.include_role:
      name: pcs_cluster
    when: fs_ha|bool

- hosts: compute
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
      
  - name: stop firewalld
    ansible.builtin.include_role:
      name: firewall

  - name: install packages
    ansible.builtin.include_role:
      name: packages

 
  - name: sleep for 60 seconds and continue with play
    wait_for:
      timeout: 60
    delegate_to: localhost
  
  - name: install packages
    ansible.builtin.include_role:
      name: nfs_client